language: node_js

node_js:
  - "10"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ninja-build
      - graphviz

install:
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - g++ -v
  - npm install
  - node scripts/genNinja
  - ninja -v