image: ubuntu

install:
- which node
- sudo apt-get update
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends install g++-7 ninja-build graphviz tesseract-ocr libtesseract-dev libleptonica-dev

- sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
- sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
- g++ -v
- node -v
- nodejs -v
- npm install

test_script:
- npm test

build: off